batch_size_perc: 0.1
dis_iter: 10
dis_nonlin: leaky_relu
dis_nonlin_kwargs:
  negative_slope: 0.1
dis_opt_args:
- 0.0001
- - 0.9
  - 0.99
dis_seed: None
dis_units:
- 20
- 2048
- 2048
- 2048
- 2048
- 2048
- 1
gen_iter: 1
gen_network_kwargs:
  add_noise_kwargs:
    lat_dim: 10
    output_dim: 128
    heteroscedastic: True
  add_noise_layer: 5
  gen_nonlin: leaky_relu
  gen_nonlin_kwargs:
    negative_slope: 0.1
  gen_units:
  - 10
  - 128
  - 128
  - 128
  - 128
  - 10
gen_opt_args:
- 0.0001
- - 0.9
  - 0.99
gen_seed: None
hold_out: 100
loss: cross_entropy
max_norm_dis: .inf
max_norm_gen: .inf
num_simulations: 10000
sample_seed: 42
stop_thresh: 0.001
