batch_size_perc: 0.1
gen_network_kwargs:
  add_noise_kwargs:
    lat_dim: 10
    output_dim: 128
    heteroscedastic: True
  add_noise_layer: 5
  gen_nonlin: leaky_relu
  gen_nonlin_kwargs:
    negative_slope: 0.1
  gen_units:
  - 10
  - 128
  - 128
  - 128
  - 128
  - 10
gen_opt_args:
- 0.0001
- - 0.9
  - 0.99
gen_seed: None
hold_out_perc: 0.2
sample_seed: 42
stop_thresh: 0.001
