
name: Formatting

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install black
          pip install flake8
          pip install isort

      - name: Run black
        run: python -m black .

      - name: Run isort
        run: python -m isort .

      - name: Run flake8
        run: python -m flake8 --max-line-length=88 --extend-ignore=E203 --per-file-ignores=*/__init__.py:F401,F403 .
