name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          pip install pytest
          pip install -r test_requirements.txt
        
      - name: Run unittests
        run: pytest -m "not slow" ./tests/
